/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_service_basicpubliclibrary_jniDemo_myJNI */

#ifndef _Included_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
#define _Included_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
