//
// Created by lenovo on 2017/9/14.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_service_basicpubliclibrary_jniDemo_myJNI */

#ifndef _Included_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
#define _Included_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_service_basicpubliclibrary_jniDemo_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lenovo_service_basicpubliclibrary_jniDemo_myJNI_sayHello
  (JNIEnv *env, jclass jobj){
  //返回一句话
      return (*env)->NewStringUTF(env,"called jni success");
  };

#ifdef __cplusplus
}
#endif
#endif

